name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
ci:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: 14
