name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
ci:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node Environment
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn

    - name: Lint project
      run: yarn lint

    - name: Build project
      run: yarn build:ssr

    - name: Test project
      run: yarn test
